name: conversor
description: Um simples conversor de bases.
version: 0.1.1
author: Victor Cassiano
homepage: https://github.com/Victorcassiano/conversor

environment:
  sdk: '>=2.8.1 <3.0.0'

#dependencies:
# path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
